data:
  root: '~/datasets/reid'
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  transforms: ['rc', 're']
  save_dir: 'logs'

model:
  name: 'bpbreid'
  load_weights: 'pretrained_models/bpbreid_market1501_hrnet32_10642.pth'
  load_config: True
  bpbreid:
    mask_filtering_training: False
    mask_filtering_testing: True # True
    learnable_attention_enabled: True
    backbone: 'hrnet32'
    test_embeddings: ['bn_foreg', 'parts']
    masks:
      dir: 'pifpaf_maskrcnn_filtering'
      preprocess: 'five_v'

test:
  evaluate: True
  batch_size: 1
  visrank: True

inference:
  enabled: True
  input_folder: '/home/leon/work_c_p_p/githubs/deep-person-reid/deep-person-reid-master/compare_images'
